#!/bin/bash

echo "Print All variables : $@"
echo "Number of variables passed :$#"
echo "Script Name: $0"
echo "Current working directory: $PWD"
echo "Home directory of current user: $HOME"
echo "which user is running this script: $USER"
echo "Hostname: $HOSTNAME"
echo "ProcessID of the current shell script: $$"
 